version: "3.9"

services:
  memcached:
    image: memcached:latest
  redis_db:
    image: redis:alpine
    volumes:
      - redis_db:/var/lib/redis
  mysql_db:
    image: mariadb
    volumes:
      - mysql_db:/var/lib/mysql
      - ./db/utf8.cnf:/etc/mysql/mariadb.conf.d/utf8.cnf
    environment:
      MYSQL_DATABASE: "echodek_app_development"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "dev"
      MYSQL_ROOT_PASSWORD: "root"
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: "bundle exec sidekiq -q critical -q high -q default -q low_priority -q mailers -"
    volumes:
      - .:/usr/src/app
      - storage:/usr/src/app/storage
      - bundle:/usr/local/bundle
      - node_modules:/usr/lib/node_modules
    depends_on:
      - mysql_db
      - redis_db
      - memcached
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=echodek_app
      - DB_HOST=mysql_db
      - EMAIL_DOMAIN=marlon.echodek.co
      - REDIS_URL=redis://redis_db:6379
      - RAILS_MAX_THREADS=5
      - CABLE_CHANNEL_PREFIX=c8o2
      - SECRET_KEY_BASE=194731158c14b377088679fa848ffd5ac8e278d2f6c452bf3697b4e401237b28bef629d7252ad2586d9c937752e9388568fb620e830d3c340e1ab56ddb0fe44b
      - MEMCACHED_URL=memcached:11211
      - RAILS_ENV=development
      - HOSTNAME=${HOSTNAME}
      - SYSADMIN_PASSWORD=password123
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "bundle exec puma"
    volumes:
      - .:/usr/src/app
      - storage:/usr/src/app/storage
      - bundle:/usr/local/bundle
      - node_modules:/usr/lib/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mysql_db
      - redis_db
      - memcached
      # - queue
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=echodek_app
      - DB_HOST=mysql_db
      - EMAIL_DOMAIN=marlon.echodek.co
      - REDIS_URL=redis://redis_db:6379
      - RAILS_MAX_THREADS=5
      - CABLE_CHANNEL_PREFIX=c8o2
      - SECRET_KEY_BASE=194731158c14b377088679fa848ffd5ac8e278d2f6c452bf3697b4e401237b28bef629d7252ad2586d9c937752e9388568fb620e830d3c340e1ab56ddb0fe44b
      - MEMCACHED_URL=memcached:11211
      - RAILS_ENV=development
      - HOSTNAME=${HOSTNAME}
      - SYSADMIN_PASSWORD=password123
      - RUN_CRON_JOBS=true

volumes:
  mysql_db:
  redis_db:
  storage:
  bundle:
  node_modules:
