name: deploy_to_production
# Expects secrets: PRODUCTION_SSH_KEY PRODUCTION_SERVER_ADDRESS SLACK_WEBHOOK_URL
on:
  push:
    tags:
      - "deploy-*"
  workflow_dispatch:

jobs:
  deploy_to_server:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - name: Fetch latest code
        uses: actions/checkout@v3.0.1
        with:
          fetch-depth: 0 # This is required or you might get an error from Dokku

      - name: Deploy to production on server 1
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://dokku@${{ secrets.PRODUCTION_SERVER_ADDRESS }}:22/app"
          ssh_private_key: ${{ secrets.PRODUCTION_SSH_KEY }}
          branch: main

  send_notifications:
    runs-on: ubuntu-latest
    needs: [deploy_to_server]
    steps:
      - name: Post to Slack
        uses: edge/simple-slack-notify@master
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel: "#development"
          status: ${{ job.status }}
          success_text: New version on the live server
          failure_text: Live server did not update
          cancelled_text: Live server update cancelled
          fields: |
            [{ "title": "Version", "value": "${env.GITHUB_REF_NAME}", "short": true },
             { "title": "Live server", "value": "https://${{ secrets.PRODUCTION_SERVER_ADDRESS }}"}]
